### ISSUE TITLE
"Open in New Tab" behavior unexpected (from index)

### ISSUE THREAD

**Issue by amy-actually** [fontana-regional-library/tawny-owl-nuxt#1]
(May be feathers, rather than tawny-owl)
1. Items in Main menu load home page in new tab (no url arguments)
2. When opening single event, info loads very slowly (may just be my local) & sometimes don't render correctly (same window, different tabs) --
       - [Event loaded from card--background-gray](https://lh3.googleusercontent.com/C0BbWzVd-tv2bbouGt4Zk0QyOz3dLtQygRfPIxtaOC46AUJ2C6HtAHi1EmTGvTs6mILk5ouFpSW6wByVt4PwoPYQUgngtmY9YDPFDNhAjrheDkG2eKDjr04_5mpursFvd178RlApb7givBz0F26i-WKtXy_fEWyySEMZSVlJU40FDAYVlsxnjMpBncQLoS1Fu4dFjh5x73X5ZgiU74JAg_kJHJI01kmCNooJGWthry2HxIJ-enfsnEkFFNDH-3S6UuzH9hcBP2vkhdJwzMLgfTTO2e1yQyxdvYXnEm6mOAEdxsThe-dGUZTQ6alFgVnKzrjEE_xEMLCeOXPJTnxPn_gqQVtdmKIEw2R3WCRG6H63CtqvBgEOspe5G_ugWICz4m6sxYUVvOqfQ6PeTYZHMEKxRR-DvqldK2wp65aHkTctVNFrSMNtp3F2qFDOO2jN6qBtqUUge2YhGR2DJ9MGrYnsi2FXuGSedhABHDVjLVBWyUxbn1axP5h1JHjXt7-M0Qo4wpFx8UEaXqFOdgYLnNNmdXorNF9PYeI8dhmy23eqtTtxhA3pSZmyrj24PfNXnjkVYo9yAqA3OEiTHcB_z0ktM-6J6jTZV63Sf7BUNO8ZO5U5tF_zIiEFlWnU7Fc8=w1806-h1769-no)
       - [Event loaded from card--background-blue](https://lh3.googleusercontent.com/rG6_STtYHNhOnMJLrJbVejVneBFjNSSGmY6p0aWxT7w8wsw3yBFrr9_w4OASZucuftGoy0jQb3QT8mEbV1x2WvsLRyeKkxMVKuldevnNDFo2zOmQ1ZU75DlbQzM8Mku7ojhJTVmuahX1ljTRCyVUTM3GujqpWD_rAYjnrQb2hMN5nSlm9F3uXRd4vy9vwuk5dcK8yj23YQungChTHvRy0c5YCqFpWJMSkHhYbdh-PQiRuAKgM2ukRaGzOXrpEMBstJ3QEPUyhkYsV6myfofvDbDQeaUYZ2dS_4ChATAiKNWiIE-JB6lZwumn6tAPKFzQk5hgmXxJMmoglHEOA0fi9CzBHtN-esf31uAnJYmV7newGqTTJFja39TYSNnNoM4cmSUKs3g6dWKrfs6IR7bSmkj2YKck4jUYaB_za8GMCrjz2CRg9p-lea7t7z1E5vVVPYM_8PovMrow2QjsWNzqB-XyVjdfCgGosDbMj97IjzE8BK3YvGFRcPQBwpywSoDSqx4JcA8ijXemjpQxkq5Y3G-jLK-RkSRJ3lu-YQ7pyTRAkK0ZcHkiHrZQ74BQVu-_YN25SK7Hy2LBB9PpvBv-Om8msLOsilOY8c9wgEvBKroNlzsGRRGgX4K9soFthRCx=w1806-h1667-no)

**Comment by amy-actually** [comment]
> - Event loaded from card--background-gray

This happens even in same tab (left-click)
---------------------------------------------
Lack of enough description/content?  fix?? add:
article {
width:100%;
}

**Comment by amy-actually** [comment]
Also reloads store on "Open in new tab"??

**Comment by michaelschofield** [comment]
@awestlib Heya Amy. Has this one sort of resolved itself?

**Comment by amy-actually** [comment]
@michaelschofield I don't see this behavior in the online beta
